# Golang CI pipeline configuration
linters:
  disable-all: true

  # Run golangci-lint linters to see the list of all linters
  # Please keep them sorted alphabetically
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocritic
    # TODO "upgrade" to gofumpt
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - nosprintfhostport
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

linters-settings:
  gocritic:
    disabled-checks:
      # TODO: re-enable after figuring out why runcommand fails on go-critic..
      - unlambda
  goconst:
    min-len: 5
