# Golang CI pipeline configuration
linters:
  disable-all: true

  # Run golangci-lint linters to see the list of all linters
  # Please keep them sorted alphabetically
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gofumpt
    - goimports
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - nosprintfhostport
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - tenv
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace

output:
  uniq-by-line: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - bodyclose

linters-settings:
  goconst:
    min-len: 5
