version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nolintlint
    - nosprintfhostport
    - predeclared
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
  settings:
    goconst:
      min-len: 5
    revive:
      rules:
        - name: var-naming
          arguments:
          - []
          - []
          - - skip-package-name-checks: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - funlen
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
