repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      # - id: go-vet
      # - id: go-lint   # go-lint is deprecated https://github.com/golang/go/issues/38968
      - id: golangci-lint # implies go-vet, https://golangci-lint.run/usage/linters
      # - id: go-critic # run by golangci-lint, in order to configure
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy
