apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dokku-storage
  namespace: dokku
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: upcloud-block-storage-maxiops