apiVersion: v1
kind: Service
metadata:
  name: dokku
  namespace: dokku
spec:
  type: NodePort
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      nodePort: 30022
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
      protocol: TCP
  selector:
    app: dokku
    app.kubernetes.io/name: dokku