#!/bin/bash

# Script to create kubeconfig from service account
mkdir -p /home/dokku/.kube
TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
CA_CERT=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt

cat > /home/dokku/.kube/config <<EOF
apiVersion: v1
kind: Config
clusters:
- name: default
  cluster:
    certificate-authority: ${CA_CERT}
    server: https://kubernetes.default.svc
contexts:
- name: default
  context:
    cluster: default
    namespace: ${NAMESPACE}
    user: default
current-context: default
users:
- name: default
  user:
    token: ${TOKEN}
EOF